server:
  port: 8083

spring:
  application:
    name: history-service
  data:
    mongodb:
      uri: mongodb://admin:admin123@localhost:27017/chatdb?authSource=admin
  kafka:
    bootstrap-servers: localhost:9094
    consumer:
      group-id: history-consumer-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.value.default.type: com.chat.common.model.ChatMessage

chat:
  kafka:
    topic: chat-messages

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
